version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      -  elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana
    environment:
       ELASTICSEARCH_URL: http://elasticsearch:9200
       ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge



# version: '2.2'
# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
#     container_name: elasticsearch
#     environment:
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       - esnet
# kibana:
#     image: docker.elastic.co/kibana/kibana:7.11.2
#     container_name: kibana
#     environment:
#       - "ELASTICSEARCH_URL=http://elasticsearch:9200"
#     ports:
#       - 5601:5601
#     networks:
#       - esnet
# volumes:
#   esdata:
#     driver: local
# networks:
#   esnet:
#     driver: bridge

# version: '2.2'
# services:
#   es01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
#     container_name: es01
#     environment:
#       - node.name=es01
#       - cluster.name=es-docker-cluster
#       - discovery.seed_hosts=es02,es03
#       - cluster.initial_master_nodes=es01,es02,es03
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - data01:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       - elastic

#   es02:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
#     container_name: es02
#     environment:
#       - node.name=es02
#       - cluster.name=es-docker-cluster
#       - discovery.seed_hosts=es01,es03
#       - cluster.initial_master_nodes=es01,es02,es03
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - data02:/usr/share/elasticsearch/data
#     networks:
#       - elastic

#   es03:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
#     container_name: es03
#     environment:
#       - node.name=es03
#       - cluster.name=es-docker-cluster
#       - discovery.seed_hosts=es01,es02
#       - cluster.initial_master_nodes=es01,es02,es03
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - data03:/usr/share/elasticsearch/data
#     networks:
#       - elastic

#   kib01:
#     image: docker.elastic.co/kibana/kibana:7.11.2
#     container_name: kib01
#     ports:
#       - 5601:5601
#     environment:
#       ELASTICSEARCH_URL: http://es01:9200
#       ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
#     networks:
#       - elastic

# volumes:
#   data01:
#     driver: local
#   data02:
#     driver: local
#   data03:
#     driver: local

# networks:
#   elastic:
#     driver: bridge